"""add transcript chunks table

Revision ID: 82be3a73e8ad
Revises: 043515d02dbf
Create Date: 2026-04-24 17:02:26.606419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '82be3a73e8ad'
down_revision: Union[str, Sequence[str], None] = '043515d02dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'transcript_chunks',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('transcript_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),

        sa.Column('speaker', sa.String(), nullable=True),
        sa.Column('text', sa.Text(), nullable=True),

        sa.Column('start_time', sa.Float(), nullable=True),
        sa.Column('end_time', sa.Float(), nullable=True),

        sa.Column('chunk_index', sa.Integer(), nullable=True),

        sa.Column('embedding', Vector(1536), nullable=True),

        sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id']),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_chunks')
    # ### end Alembic commands ###
